apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
# spec customizes how the deployment will behave
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
    # Must match up with whatever we put inside the spec for the deployment itself.
      labels:
        component: server
    spec:
      containers:
      - name: server
      # Need to add env variables to tell express api how to connect
      # to postgres and redis
        image: orange29/multi-server
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: '6379'
          - name: PGUSER
            # Technically not good form
            value: postgres
          # From postgres-cluster-ip-service.yaml
          - name: PGHOST
            value: postgres-cluster-ip-service
          - name: PGPORT
            value: '5432'
          - name: PGDATABASE
            value: postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                # The Secrets name
                name: pgpassword
                # Key is from the kuebctl create secret command.  Note:  The name of
                # the key can be different from the env variable.
                key: PGPASSWORD
