apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    # spec configures what this pod is running
    spec:
      containers:
      - name: worker
        image: orange29/multi-worker
        env:
          # From redis-cluster-ip-service.yaml
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: '6379'
